### ISSUE TITLE
detect_vba_macros false-positive with 'Attribut' string in stream

### ISSUE THREAD

**Issue by LeMurphant** [decalage2/oletools#247]
I lack experience in the OLE format so I am sorry if anything I say is blatanly wrong.

I am getting false-positives with the existance of macros with function *detect_vba_macros()* in olevba3.py with Word documents that appear to have the entire payload of the file in a stream. If the word *Attribut* is contained in the file, the following hits
` if 'Attribut' in data.decode('utf-8', 'ignore'):`
e.g. in the line 
`concernant (i) l’attribution`

I understand that these files might be misformatted, but libreoffice opens them without a problem without a macro warning. Is that something that might be addressed?

I cannot share the samples I have at this point for confidentiality reasons but I can try to find one that I can share if it helps.

**Comment by decalage2** [comment]
You are right, this is because olevba uses two methods to detect macros: First by checking storage names, second by looking for the 'Attribut' keyword (as oledump does), in case the first method fails.
This bug is both in olevba and olevba3.

Potential solutions:
- look for 'Attribut\x00' (null byte very unlikely to be in the document text)
- check the presence of other keywords such as 'VB_Nam\x00'
- check if the stream path is not a known non-VBA stream, such as 'WordDocument', '1Table', etc.

**Comment by decalage2** [comment]
BTW, there's another issue with the olevba3 code: it converts the data to unicode whereas it's binary data, not text. It should look for bytes keywords instead. => to be fixed at the same time.

**Comment by LeMurphant** [comment]
The _null byte_ fix seems quite reasonnable and fixes most use cases. From my limited testing on the raw documents, _VB_Nam\x00_ looks good, although I have not had hits either way with _WordDocument_ or _1Table_.
