### ISSUE TITLE
rtfobj: parsing issue with control words "\pnaiu" & "\pnaiud"

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#327]
Reported by @ShiaoQu17: https://twitter.com/ShiaoQu17/status/1009999002517962752

"\pnaiu" & "\pnaiud" Two "Flag" type control words that consume data from its group. eg. (in objdata) "0102{\*\pnaiu 1234}0304" => "01020304"

Sample:
- https://www.hybrid-analysis.com/sample/9ac09ea38c9cf11ca13a2c3dbdcfbe0fe4a15cb609be451f7159ecebdd20d311
- https://www.virustotal.com/#/file/9ac09ea38c9cf11ca13a2c3dbdcfbe0fe4a15cb609be451f7159ecebdd20d311/detection

**Comment by Maijin** [comment]
This is fixed https://github.com/decalage2/oletools/blob/master/oletools/rtfobj.py#L89

**Comment by decalage2** [comment]
Sometimes I just forget to close issues on Github after fixing them...

**Comment by Maijin** [comment]
Yeah I have commented to some more of them if you can close them that would really help because it's hard for contributors to know where to start when so many are already fixed 👍.

See:

- https://github.com/decalage2/oletools/issues/240
- https://github.com/decalage2/oletools/issues/184
- https://github.com/decalage2/oletools/issues/152
- https://github.com/decalage2/oletools/issues/155
- https://github.com/decalage2/oletools/issues/394
- https://github.com/decalage2/oletools/issues/49

And this one looks like a duplicate

- https://github.com/decalage2/oletools/issues/331
