### ISSUE TITLE
Require pyparsing >= 2.1.0 rather 2.2.0

### ISSUE THREAD

**Issue by robert-scheck** [decalage2/oletools#481]
Do you see any chance to lower the requirement for pyparsing >= 2.2.0 to 2.1.0? Even RHEL 8 has only 2.1.0, which would exclude oletools from getting packaged in EPEL 8.

**Comment by decalage2** [comment]
I will check if it works with pyparsing 2.1.0. The issue is, when installing python packages with pip (which is the way I usually install oletools), I prefer to force pip to install the most recent versions, to avoid staying with old buggy dependencies. I understand it's a different situation when using Linux distribution packages instead of pip.
However, we have two places where dependencies are listed: in the setup.py script (which is automatically used by pip), and the requirements.txt file (which is only used when manually forcing pip to read it).
@robert-scheck, which list of dependencies is a problem for you, the one in setup.py, or requirements.txt?
If it's requirements.txt, then I can have more relaxed requirements there, while keeping setup.py as-is.

**Comment by robert-scheck** [comment]
@decalage2, just changing the dependency in `requirements.txt` file still leads to this issue:

```
+ /usr/bin/python3.6 setup.py test
running test
Searching for pyparsing>=2.2.0
Reading https://pypi.org/simple/pyparsing/
Download error on https://pypi.org/simple/pyparsing/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't retrieve index page for 'pyparsing'
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for pyparsing>=2.2.0
error: Could not find suitable distribution for Requirement.parse('pyparsing>=2.2.0')
```

So the desired change would be `setup.py` here.

**Comment by decalage2** [comment]
OK, let's see if it works with pyparsing 2.1.0.
